### PR TITLE
Convert unit tests to gtest

### LINKED ISSUE #282: Convert unit tests from cppunit to googletest
Unit tests are currently crashing, (@rwcarlsen or @brianmoose) I suspect we're left alone here because we're still on cppunit. Let's migrate the tests to gtest.

### PR DESCRIPTION
**Pull request by dschwen**
Testing on the test boxes...

Closes #282

### CODE REVIEW

File: unit/src/DiscreteFissionPDFTest.C [hunk 1]
```diff
@@ -180,45 +177,26 @@ DiscreteFissionPDFTest::sampleFissionPKA()
   auto maxerror = std::max_element(error.begin(), error.end());
 
   //check if total energy is conserved
-  CPPUNIT_ASSERT( std::abs(total_energy / max - true_energy) < 1.0 );
+  ASSERT_TRUE(std::abs(total_energy / max - true_energy) < 1.0);
```
Comment (rwcarlsen) [inline unit/src/DiscreteFissionPDFTest.C]: You can augment assertions like this to add custom output when they fail:

```c++
ASSERT_TRUE(false) << "oh no - how could false be not true?";
```
...(in case you weren't aware already).

Also, I usually use ``EXPECT_[bla]`` instead of ``ASSERT_[bla]`` because the latter immediately terminates execution of everything in the ``TEST[_F]`` function while the former allows you to collect output on all of the checks before terminating.  Use whatever you think is most appropriate.

File: unit/include/DiscreteFissionPDFTest.h [hunk 2]
```diff
@@ -16,21 +16,31 @@
...
 #include "DiscreteFissionPKAPDF.h"
 #include "MooseRandom.h"
 
-class DiscreteFissionPDFTest : public CppUnit::TestFixture
-{
-  CPPUNIT_TEST_SUITE( DiscreteFissionPDFTest );
+#include <gtest/gtest.h>
 
-  CPPUNIT_TEST( sampleFissionPKA );
+class DiscreteFissionPDFTest : public ::testing::Test
```
Comment (rwcarlsen) [inline unit/include/DiscreteFissionPDFTest.h]: It looks like this class has no state - so there is no point on having it as a test fixture.  You could just take the member functions and make them plain functions in the .C file.

File: unit/src/DiscreteFissionPDFTest.C (hunk 1 above)
Comment (dschwen) [reply unit/src/DiscreteFissionPDFTest.C]: Thanks, Robert, I'll make the changes accordingly!

**Comment by dschwen** [comment]
@snschune, this fixes the crashing unit test (and converts it to gtest). The issue was the stuff removed in 097dfbb
