### PR TITLE
Time step size & some minor items

### LINKED ISSUE #311: Need check on Z & M in rasterizer
`Z <= M` and usually `Z < M`. I made the mistake of entering one `Z` for `M` and it simply crashed. This should be checked to make it easier to find input errors.

### PR DESCRIPTION
**Pull request by snschune**
closes #311 #316 #317.

### CODE REVIEW

File: src/dirackernels/MyTRIMDiracSource.C [hunk 1]
```diff
@@ -52,5 +54,5 @@ MyTRIMDiracSource::addPoints()
 Real
 MyTRIMDiracSource::computeQpResidual()
 {
-  return -_test[_i][_qp];
+  return -_test[_i][_qp] / _rasterizer.getTrimParameters().last_executed_dt;
```
Comment (dschwen) [inline src/dirackernels/MyTRIMDiracSource.C]: This does not seem right. Off the cuff I'd think it'd be ratio between last executed dt and current dt...

Comment (snschune) [reply src/dirackernels/MyTRIMDiracSource.C]: `_test[_i][_qp] ` has units of defects but the kernel must have units of defects / time.

Comment (dschwen) [reply src/dirackernels/MyTRIMDiracSource.C]: Yeah, you're right
